apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rabbitmqs.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: RabbitMQ
    listKind: RabbitMQList
    plural: rabbitmqs
    singular: rabbitmq
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1alpha1
    served: true
    storage: true
